#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCSampleUnitTestPagerView;
    
    #line 2 "..\..\Views\Cricketers\Index.cshtml"
    using PagedList;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Cricketers\Index.cshtml"
    using PagedList.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Cricketers/Index.cshtml")]
    public partial class _Views_Cricketers_Index_cshtml : System.Web.Mvc.WebViewPage<PagedList.IPagedList<MVCSampleUnitTestPagerView.Models.CricketerProfile>>
    {
        public _Views_Cricketers_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Cricketers\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n            Name\r\n        </th>\r\n        <th>\r\n       " +
"     Test Runs\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 23 "..\..\Views\Cricketers\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Views\Cricketers\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\Cricketers\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.TestRuns));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 32 "..\..\Views\Cricketers\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 34 "..\..\Views\Cricketers\Index.cshtml"
Write(Html.PagedListPager(Model, page => Url.Action("Index", new { page = page })));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
